config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'} # Tells route to use specification controller for users
  
  resources :users do
    resource :profile # ever user only have 1 profile
  end
  
  resources :contacts # Auto generate many(7 types of controller actions: index, show, new, edit, destory, update, create) routes, Use 'bundle exec rake routes' to check the routes
  get '/about' => 'pages#about'
  root 'pages#home' # Keep root in the button

end

app/models/profile.rb
class Profile < ActiveRecord::Base
    
    belongs_to :user
    
    # Paperclip setting
    has_attached_file :avatar, styles: {medium: "300x300", thumb: "100x100"}, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    before_action :authenticate_user!, only: [:new, :edit] # before_action<Rails, before below action; :authenticate_user<Stripe; only while new and edit action
    before_action :only_current_user
    
    def new
        # Form to user allow them to fill their own profile.
        # 'build' is rails public method; after we nested profile with users, we are able to use build_profile.
        @user = User.find(params[:user_id]) # This to make sure user who is log-in
        # @profile = @user.build_profile # This command will clean up profile data every time while user link to /users/:user_id/profile/new
        @profile = Profile.new # This is not, it only reset Profile after submit
        @user_email = @user[:email]
    end
    
    def create
        # profile_params is to collect all data on the form.
        @user = User.find(params[:user_id])
        if @user == current_user 
            @profile = @user.build_profile(profile_params)
            if @profile.save # if profile alreade saved,  
                flash[:success] = "Profile Updated!"
                redirect_to user_path(params[:user_id])
            else
                render action: :new # Run new method
                flash[:success] = "Profile Created!"
                redirect_to user_path(params[:user_id])
            end
        else
           flash[:warning] = "You are not in a correct url"
           redirect_to new_user_profile_path(params[:user_id])
        end
    end
    
    def edit 
        @user = User.find(params[:user_id])
        @profile = @user.profile # pull out the user profilegi
    end
    
    def update
       @user = User.find(params[:user_id])
       @profile = @user.profile
       if @profile.update_attributes(profile_params) # update_attributes is a rails method. It will save any changed to DB
       flash[:success] = "Profile Updated!"
       redirect_to user_path(params[:user_id])
        else
            render action: :edit # if save fail, stay in edit page
        end
    end
    
    private
        def profile_params # white list
            params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
        end
        
        def only_current_user
            @user = User.find(params[:user_id])
            redirect_to(root_url) unless @user == current_user
        end
end

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: {multipart: true} do |f| %> <!-- Since this is a singular resource path, we have to specify the path -->
    <fieldset class="form-group">
        <%= f.label :first_name %>
        <%=f.text_field :first_name, class: 'form-control', placeholder: 'First name: ' %>
    </fieldset>
    <fieldset class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last name:' %>
    </fieldset>
    <fieldset class="form-group">
        <%= f.label :avatar %>
        <%=f.file_field :avatar, class: 'form-control', placeholder: 'First name: ' %>
    </fieldset>
    <fieldset class="form-group">
        <%= f.label 'Your Job title:' %>
        <%= f.select :job_title, ['---Please sellect one---','Entrepreneur', 'Developer', 'Investor', 'Manager'], {}, class: 'form-control' %>
        <!-- {} is for other option; if not goinig to use it, need to leave it empty-->
    </fieldset>
    <fieldset class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control', placeholder: '**-******** or 09********:' %>
    </fieldset>
    <fieldset class="form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: 'form-control', placeholder: 'If you need specify contact email or just leave it empty' %>
    </fieldset>
    <fieldset class="form-group">
        <%= f.label 'Talk about more of yourself:' %>
        <%= f.text_area :description, class: 'form-control', placeholder: 'Once upon a time ...' %>
    </fieldset>
    <div class="container">
        <%= f.submit "Update Profile", class:'actions btn btn-success' %>
    </div>
<%end%>

app/views/profiles/edit.html.erb
<!-- Create new profile -->
    <div class ="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="alert alert-success text-center">
                <h2>Update Your Profile</h2>
            </div>
            <div class="jumbotron">
            <%= render 'form' %>
            </div>
        </div>
    </div>
    <% flash[:success] = "Hi #{@user_email}, welcome to your profile page !" %>

app/views/profiles/new.html.erb
<!-- Create new profile -->
<% if @user == current_user %>
    <div class ="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="alert alert-success text-center">
                <h2>Create Your Profile</h2>
            </div>
            <div class="jumbotron">
            <%= render 'form' %>
            </div>
        </div>
    </div>
    <% flash[:success] = "Hi #{@user_email}, welcome to your profile page !" %>
<%else%>
    <% flash[:danger] = "You were not in a correct link" %>
    <div class="col-md-offset-1">
        <%= link_to new_user_profile_path(current_user), method: :get, class: 'btn btn-info' do %> <!-- current_user is provide by Devise -->
        Back to your own profile
        <%end%>
    </div>
<%end%>