config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'} # Tells route to use specification controller for users
  
  resources :users do
    resource :profile # ever user only have 1 profile
  end
  
  resources :contacts # Auto generate many(7 types of controller actions: index, show, new, edit, destory, update, create) routes, Use 'bundle exec rake routes' to check the routes
  get '/about' => 'pages#about'
  root 'pages#home' # Keep root in the button

end

app/views/pages/about.html.erb
<h2>About me</h2>

app/views/pages/home.html.erb
<div class="container-fluid">
    <div class="jumbotron text-center">
        <h1>Welcome to My First RoR App</h1>
        <h3>This would be good practice for Dayeasier!!</h3>
    </div>
    <div class="row">
        <% if user_signed_in? %>
            <div class="container">
                <% if @user.profile %>
                    <div class="card col-md-4" id="profile-card">
                        <div class="card-block">
                            <div class="card-title text-center">
                                <h2><%= @user.profile.first_name %> <%= @user.profile.last_name %></h2>
                            </div>
                            <p class="card-text">Job Title: <%= @user.profile.job_title %></p>
                            <!-- Let current user can read more profile -->
                            <% if @user == current_user %>
                                <p class="card-text">Phone: <%= @user.profile.phone_number %></p>
                                <p class="card-text">Contact e-mail: <%= @user.profile.contact_email %></p>
                                <p class="card-text">About me: <%= @user.profile.description %></p>
                            <%end%>
                            <div class="container">
                                <%= link_to edit_user_profile_path(current_user), class:'btn btn-info', method: :get do %> <!-- current_user is provide by Devise -->
                                Update your profile
                                <%end%>
                            </div>
                        </div>
                    </div>
                    
                <%else%>
                    <div class="alert alert-danger">
                        <p>You didn't set your profile yet! Please create your profile for others can find you !</p>
                    </div>
                    <%= link_to new_user_profile_path(current_user), class:'btn btn-info', method: :get do %> <!-- current_user is provide by Devise -->
                        create your profile
                    <%end%>
                <%end%>
                <div class="card col-md-6 col-md-offset-2">
                    <div class="container">
                        <div class="card" id="profile-slider">
                            <div class="card-block">
                                <div class="card-title text-center" id="profile-title">
                                    <h2><%= @rand_user.profile.first_name %> <%= @rand_user.profile.last_name %></h2>
                                </div>
                                <p class="card-text">Job title: <%= @rand_user.profile.job_title %></p>
                                <!-- Let pro account(plan_id=2) can read more profile -->
                                <% if current_user.plan_id == 2 %>
                                    <p class="card-text">Phone number: <%= @rand_user.profile.phone_number %></p>
                                    <p class="card-text">Contact e-mail: <%= @rand_user.profile.contact_email %></p>
                                    <p class="card-text">Dscription: <%= @rand_user.profile.description %></p>
                                <%end%>
                                <nav class="navbar navbar-light bg-faded">
                                    <a herf="#" class="arrow-preview"><<<</a>
                                    <a herf="#" class="arrow-next pull-xs-right">>>></a>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% else %>
            <div class="col-sm-6 text-center">
                <div class="card">
                    <img class="card-img-top" src="http://images.freeimages.com/images/previews/674/freedom-1314475.jpg" height="200px" alt="Card image cap">
                    <div class="card-block">
                        <h4 class="card-title">Basic Membership</h4>
                        <p class="card-text">Sign up to get free basic access</p>
                        <%= link_to new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-info btn-lg btn-block', method: :get do %>
                        <h4>Sign Up Free</h4>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 text-center">
                <div class="card">
                    <img class="card-img-top" src="http://i.istockimg.com/file_thumbview_approve/53544776/6/stock-photo-53544776-girl-having-fun.jpg" height="200px" alt="Card image cap">
                    <div class="card-block">
                        <h4 class="card-title">Paid Membership</h4>
                        <p class="card-text">Become a pro user!!</p>
                        <%= link_to new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block active', method: :get do %>
                        <h4>Sign Up to PRO</h4>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>