config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'} # Tells route to use specification controller for users
  
  resources :users do
    resource :profile # ever user only have 1 profile
  end
  
  resources :contacts # Auto generate many(7 types of controller actions: index, show, new, edit, destory, update, create) routes, Use 'bundle exec rake routes' to check the routes
  get '/about' => 'pages#about'
  root 'pages#home' # Keep root in the button

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaasPractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
  <!-- Bootstrap is developed mobile first -->
  <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
</head>
<body>

  <nav class="navbar navbar-dark bg-inverse">
    <!--<div class=container>-->
      <a class="navbar-brand" href="/" id="brand-color">DAY EASIER</a>
      <ul class="nav navbar-nav">
        <li class="nav-item active">
          <!--<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>-->
          <%= link_to root_path, class: 'nav-link' do %>
            <span class="sr-only">(current)</span>
            Home
          <% end %>

        </li>
        <li class="nav-item">
          <!--<a class="nav-link" href="/about">About</a>-->
          <%= link_to about_path, class: 'nav-link' do %>
          <i class="fa fa-users"></i><!-- Added Font Awsome and raplaced 'About', need to add gem and import .scss-->
          About Us
          <% end %>
        </li>
        <li class="nav-item">
          <!--<a class="nav-link" href="#">Contact Us</a>-->
          <%= link_to new_contact_path, class:'nav-link' do %>
          Contact Us
          <%end%>
        </li>
      </ul>
      <form class="form-inline pull-xs-right">
        <input class="form-control" type="text" placeholder="Search">
        <button class="btn btn-success-outline" type="submit">Search</button>
        <a>
          <!--<a class="nav-link" href="/users/sign_in">LogIn</a>-->
          <% if current_user %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-warning', role: 'button' do %>
              Log Out
            <% end %>
            <%= link_to user_path(current_user), method: :get, class: 'btn' do %>
              <%= image_tag @user.profile.avatar.url(:thumb), class: 'profile-picture' %>
            <%end%>
          <% else %>
            <%= link_to new_user_session_path, class: 'btn btn-success', role: 'button', method: :get do %>
              Log In
            <% end %>
            <!--<%= link_to new_user_registration_path, class: 'btn btn-info-outline', role: 'button', method: :get do %>-->
            <!--Sign Up-->
            <!--<% end %>-->
          <% end %>
        </a>
      </form>
    <!--</div>-->
  </nav>

  <div class="container-fluid"> <!-- Get lay out properly -->
    <div class="container">
      <% flash.each do |k, v|%> <!-- !! No equal sign before flash.each !! -->
        <%= content_tag :div, v, class: "alert alert-#{k}", role: "alert" %>
      <%end%>
    </div>
  
    <%= yield %> <!--Get anything from ruby controller(pages)-->
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>
</body>



</html>